"""Regenerate the frontend's static config copies + embedded configs.js.

Run this whenever backend/config/*.json changes:
    python tools/sync_configs.py

- frontend/static/config/countries/uk.json   (copy)
- frontend/static/config/difficulty.json     (copy)
- frontend/static/config/configs.js          (embedded globals, works on file://)
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CFG = ROOT / "backend" / "config"
DEST = ROOT / "frontend" / "static" / "config"

uk = json.loads((CFG / "countries" / "uk.json").read_text(encoding="utf-8"))
diff = json.loads((CFG / "difficulty.json").read_text(encoding="utf-8"))

(DEST / "countries").mkdir(parents=True, exist_ok=True)
(DEST / "countries" / "uk.json").write_text(json.dumps(uk, ensure_ascii=False, indent=2), encoding="utf-8")
(DEST / "difficulty.json").write_text(json.dumps(diff, ensure_ascii=False, indent=2), encoding="utf-8")

configs_js = (
    "/* Generated by tools/sync_configs.py — do not edit by hand.\n"
    "   Embedded so the pure client-side build works even on file:// (no fetch). */\n"
    "globalThis.SHIPPED_CONFIGS = {\n"
    f"  countries: {json.dumps({'uk': uk}, ensure_ascii=False)},\n"
    f"  difficulties: {json.dumps(diff, ensure_ascii=False)},\n"
    "};\n"
)
(DEST / "configs.js").write_text(configs_js, encoding="utf-8")
print("configs synced: uk.json, difficulty.json, configs.js")
